; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-amd-amdpal -mcpu=gfx942 < %s | FileCheck %s
;
; Verify that vector atomic loads are lowered correctly on AMDGPU.
; shouldCastAtomicLoadInIR casts these to integer atomic loads, which
; SelectionDAG can then select.

define <2 x half> @load_atomic_v2f16_global_monotonic(ptr addrspace(1) %ptr) {
; CHECK-LABEL: load_atomic_v2f16_global_monotonic:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    global_load_dword v0, v[0:1], off sc0 sc1
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %r = load atomic <2 x half>, ptr addrspace(1) %ptr monotonic, align 4
  ret <2 x half> %r
}

define <2 x bfloat> @load_atomic_v2bf16_global_monotonic(ptr addrspace(1) %ptr) {
; CHECK-LABEL: load_atomic_v2bf16_global_monotonic:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    global_load_dword v0, v[0:1], off sc0 sc1
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %r = load atomic <2 x bfloat>, ptr addrspace(1) %ptr monotonic, align 4
  ret <2 x bfloat> %r
}

define <2 x float> @load_atomic_v2f32_global_monotonic(ptr addrspace(1) %ptr) {
; CHECK-LABEL: load_atomic_v2f32_global_monotonic:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    global_load_dwordx2 v[0:1], v[0:1], off sc0 sc1
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %r = load atomic <2 x float>, ptr addrspace(1) %ptr monotonic, align 8
  ret <2 x float> %r
}
