; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64-linux-gnu -O1 %s -o - | FileCheck %s
;
; Verify that vector atomic loads are lowered correctly on AArch64.
; shouldCastAtomicLoadInIR casts these to integer atomic loads, which
; SelectionDAG can then select.

define <2 x half> @load_atomic_v2f16_monotonic(ptr %ptr) {
; CHECK-LABEL: load_atomic_v2f16_monotonic:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr s0, [x0]
; CHECK-NEXT:    ret
  %r = load atomic <2 x half>, ptr %ptr monotonic, align 4
  ret <2 x half> %r
}

define <2 x float> @load_atomic_v2f32_monotonic(ptr %ptr) {
; CHECK-LABEL: load_atomic_v2f32_monotonic:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldr x8, [x0]
; CHECK-NEXT:    fmov d0, x8
; CHECK-NEXT:    ret
  %r = load atomic <2 x float>, ptr %ptr monotonic, align 8
  ret <2 x float> %r
}

define <2 x double> @load_atomic_v2f64_monotonic(ptr %ptr) {
; CHECK-LABEL: load_atomic_v2f64_monotonic:
; CHECK:       // %bb.0:
; CHECK-NEXT:  .LBB2_1: // %atomicrmw.start
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldxp x9, x8, [x0]
; CHECK-NEXT:    stxp w10, x9, x8, [x0]
; CHECK-NEXT:    cbnz w10, .LBB2_1
; CHECK-NEXT:  // %bb.2: // %atomicrmw.end
; CHECK-NEXT:    fmov d0, x9
; CHECK-NEXT:    mov v0.d[1], x8
; CHECK-NEXT:    ret
  %r = load atomic <2 x double>, ptr %ptr monotonic, align 16
  ret <2 x double> %r
}
